package main;

import Entites.Forgeron;
import Entites.GrossePierre;
import Entites.Mage;
import Entites.Maire;
import Entites.Marchant;
import Entites.Villageois;
import donnees.Progression;
import monstres.ChauveSouris;
import monstres.Demon;
import monstres.Geant;
import monstres.Golem;
import monstres.RoiSquelette;
import monstres.Orc;
import monstres.Slime;
import object.BouclierFer;
import object.BouclierRenforce;
import object.Chaussure;
import object.Cle;
import object.Coeur;
import object.Coffre;
import object.Emeraude;
import object.EpeeLegendaire;
import object.EpeeLourde;
import object.EpeeNormale;
import object.HacheEnPierre;
import object.Lance;
import object.Lanterne;
import object.Lit;
import object.Mana;
import object.Pieces;
import object.Pioche;
import object.Porte;
import object.PorteFer;
import object.PotionSoin;
import terrain.ArbreCassable;
import terrain.MurCassable;
import terrain.Plaque;

public class GererObject {

	Ecran ecran;
	
	public GererObject(Ecran ecran) {
		this.ecran = ecran;
	}
	
	public void setObjects() {
		
		int mapNum = 0;
		int i = 0;
		
		ecran.obj[mapNum][i] = new Cle(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*56;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*74;
		i++;
		ecran.obj[mapNum][i] = new Cle(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*95;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*21;
		i++;
		ecran.obj[mapNum][i] = new Pieces(ecran, 3);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*98;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*1;
		i++;
		ecran.obj[mapNum][i] = new Mana(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*47;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*38;
		i++;
		ecran.obj[mapNum][i] = new Coeur(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*51;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*38;
		i++;
		ecran.obj[mapNum][i] = new BouclierRenforce(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*14;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*63;
		i++;
		ecran.obj[mapNum][i] = new HacheEnPierre(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*36;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*13;
		i++;
		ecran.obj[mapNum][i] = new PotionSoin(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*16;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*17;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*90;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*65;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*84;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*38;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*38;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*41;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*50;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*75;
		i++;
		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new EpeeNormale(ecran));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*92;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*66;
		i++;
		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new Pieces(ecran, 3));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*18;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*98;
		i++;
		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new BouclierRenforce(ecran));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*19;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*98;
		i++;
		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new Chaussure(ecran));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*20;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*98;
		i++;
		ecran.obj[mapNum][i] = new Lit(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*20;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*65;
		i++;
		ecran.obj[mapNum][i] = new Lanterne(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*72;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*31;
		i++;

		mapNum = 2;
		i = 0;

		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new EpeeLourde(ecran));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*83;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*13;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*39;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*37;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*40;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*37;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*88;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*14;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*30;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*44;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*30;
		i++;
		ecran.obj[mapNum][i] = new Pioche(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*53;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*28;
		i++;
		ecran.obj[mapNum][i] = new Cle(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*87;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*86;
		i++;
		ecran.obj[mapNum][i] = new Cle(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*41;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*53;
		i++;

		mapNum = 3;
		i = 0;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*11;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*17;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*75;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*46;
		i++;
		ecran.obj[mapNum][i] = new HacheEnPierre(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*68;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*94;
		i++;
		ecran.obj[mapNum][i] = new Coffre(ecran);
		ecran.obj[mapNum][i].initialiserContenu(new Lance(ecran));
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*14;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*79;
		i++;
		ecran.obj[mapNum][i] = new BouclierFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*53;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*11;
		i++;

		mapNum = 4;
		i = 0;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*56;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*34;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*56;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*79;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*34;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*79;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*54;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*30;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*55;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*30;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*86;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*55;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*91;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*40;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*92;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*40;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*72;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*59;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*75;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*73;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*80;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*91;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*38;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*92;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*15;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*92;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*84;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*80;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*70;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*9;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*59;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*13;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*53;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*7;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*45;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*14;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*43;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*6;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*33;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*7;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*33;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*9;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*18;
		i++;
		ecran.obj[mapNum][i] = new Porte(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*2;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*5;
		i++;
		ecran.obj[mapNum][i] = new Coeur(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*72;
		i++;
		ecran.obj[mapNum][i] = new Mana(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*34;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*72;
		i++;
		ecran.obj[mapNum][i] = new Lit(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*73;
		i++;
		ecran.obj[mapNum][i] = new PotionSoin(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*34;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*73;
		i++;
		


		mapNum = 8;
		i = 0;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*66;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*48;
		i++;

		mapNum = 9;
		i = 0;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*23;
		i++;
		ecran.obj[mapNum][i] = new PorteFer(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*48;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*23;
		i++;
		ecran.obj[mapNum][i] = new EpeeLegendaire(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*48;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*22;
		i++;
		ecran.obj[mapNum][i] = new Emeraude(ecran);
		ecran.obj[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.obj[mapNum][i].carteY = ecran.tailleFinale*22;
		i++;
	}
	
	public void setMage() {
		
		int mapNum = 0;
		int i = 0;
		
		ecran.mage[mapNum][i] = new Mage(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*90;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*70;
		i++;
		ecran.mage[mapNum][i] = new Mage(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*40;
		i++;
		
		mapNum = 1;
		i = 0;
		ecran.mage[mapNum][i] = new Marchant(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;

		mapNum = 2;
		i = 0;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*43;
		i++;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*19;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*51;
		i++;

		mapNum = 3;
		i = 0;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*71;
		i++;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*83;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*93;
		i++;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*69;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*10;
		i++;

		mapNum = 4;
		i = 0;
		ecran.mage[mapNum][i] = new Forgeron(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*8;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*24;
		i++;
		ecran.mage[mapNum][i] = new Maire(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*58;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*21;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*8;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*92;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*7;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*78;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*6;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*68;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*9;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*56;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*6;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*42;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*7;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*20;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*3;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*2;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*26;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*84;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*61;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*75;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*57;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*65;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*77;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*75;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*78;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*93;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*93;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*89;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*93;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*37;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*34;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*60;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*38;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*67;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*40;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*69;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*30;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*72;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*36;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*74;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*58;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*44;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*47;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*60;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*51;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*55;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*54;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*53;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*56;
		i++;
		ecran.mage[mapNum][i] = new Villageois(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*18;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;

		mapNum = 8;
		i = 0;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*50;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*46;
		i++;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*60;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*46;
		i++;
		ecran.mage[mapNum][i] = new GrossePierre(ecran);
		ecran.mage[mapNum][i].carteX = ecran.tailleFinale*68;
		ecran.mage[mapNum][i].carteY = ecran.tailleFinale*46;
		i++;
	}
	
	public void setMonstre() {
		
		int mapNum = 0;
		int i = 0;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*47;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*63;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*63;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*51;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*63;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*50;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*67;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*48;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*78;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*50;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*78;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*69;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*46;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*69;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*53;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*59;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*77;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*37;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*95;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*30;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*88;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*20;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*90;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*20;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*75;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*17;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*94;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*12;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*88;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*10;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*94;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*6;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*82;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*5;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*84;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*3;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*70;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*3;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*30;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*20;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*26;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*49;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*67;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*37;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*10;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 1);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*39;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*4;
		i++;

		mapNum = 2;
		i = 0;
		ecran.monstre[mapNum][i] = new Orc(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*41;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*45;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*41;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*11;
		i++;
		ecran.monstre[mapNum][i] = new Orc(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*46;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*12;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*47;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*26;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*23;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*41;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*28;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*9;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*52;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*11;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*55;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*13;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*51;
		i++;
		ecran.monstre[mapNum][i] = new Slime(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*35;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*52;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*87;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*15;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*23;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*62;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*39;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*57;
		i++;
		ecran.monstre[mapNum][i] = new Geant(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*28;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*89;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*40;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*36;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*33;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*34;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*52;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*31;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*44;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 2);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*48;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*44;
		i++;

		mapNum = 3;
		i = 0;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*7;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*86;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*61;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*36;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*43;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*47;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*61;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*53;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*76;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*70;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*73;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*89;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*81;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*91;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*81;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*84;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*62;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*85;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*95;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*68;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*84;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*65;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*86;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*23;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*62;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*41;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*18;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*53;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*8;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*12;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*72;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*15;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*72;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*20;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*83;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*76;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*89;
		i++;
		ecran.monstre[mapNum][i] = new Golem(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*85;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*88;
		i++;
		ecran.monstre[mapNum][i] = new RoiSquelette(ecran, 3);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*10;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*7;
		i++;

		mapNum = 4;
		i = 0;



		mapNum = 8;
		i = 0;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*20;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*61;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*24;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*65;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*17;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*85;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*35;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*85;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*44;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*86;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*57;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*93;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*63;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*49;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*20;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*22;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*21;
		i++;
		ecran.monstre[mapNum][i] = new ChauveSouris(ecran, 9);
		ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*74;
		ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*23;
		i++;

		
		i = 0;
		mapNum = 9;
		if (!Progression.roiDemonBattu) {
			ecran.monstre[mapNum][i] = new Demon(ecran, 10);
			ecran.monstre[mapNum][i].carteX = ecran.tailleFinale*47;
			ecran.monstre[mapNum][i].carteY = ecran.tailleFinale*28;
			i++;
		}
	}
	
	public void setElementInteractif() {
		
		int mapNum = 0;

		int i = 0;
		
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 91, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 92, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 93, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 66);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 68);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 69);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 70);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 71);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 72);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 73);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 74);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 75);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 94, 76);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 95, 76);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 88);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 89);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 90);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 91);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 92);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 49, 93);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 47);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 46);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 45);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17,44);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 43);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 42);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 41);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 40);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 39);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 38);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 37);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 36);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 35);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 34);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 33);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 32);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 31);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 30);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 17, 29);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 18, 29);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 18, 28);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 18, 27);
		i++;

		mapNum = 2;
		i = 0;

		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 39, 75);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 39, 78);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 39, 79);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 39, 82);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 28, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 28, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 28, 66);
		i++;
		ecran.iTerrain[mapNum][i] = new ArbreCassable(ecran, 28, 67);
		i++;

		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 78, 64);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 78, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 79, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 80, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 81, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 82, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 83, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 84, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 85, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 86, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 87, 65);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 88, 66);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 88, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 87, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 86, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 85, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 84, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 83, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 82, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 81, 67);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 7, 53);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 32, 37);
		i++;

		mapNum = 3;
		i = 0;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 15, 84);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 15, 85);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 81, 24);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 81, 25);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 22, 29);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 22, 30);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 23, 29);
		i++;
		ecran.iTerrain[mapNum][i] = new MurCassable(ecran, 23, 30);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 32, 82);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 62, 92);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 55, 4);
		i++;


		mapNum = 8;
		i = 0;

		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 62, 45);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 64, 45);
		i++;
		ecran.iTerrain[mapNum][i] = new Plaque(ecran, 66, 45);
		i++;
	}
}
